apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cnfdt17-subscription
  namespace: cnfdt17-subscription
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cnfdt17-subscription
