apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cu-cnfde2-subscription
  namespace: cu-cnfde2-subscription
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cu-cnfde2-subscription
