---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cnfde6-cu-subscription
  namespace: cnfde6-cu-subscription
spec:
  type: GitHub
  pathname: https://github.com/serngawy/ztp-ran-manifests
