---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cnfde9-du-subscription
  namespace: cnfde9-du-subscription
spec:
  type: GitHub
  pathname: https://github.com/serngawy/ztp-ran-manifests
