---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: du-subscription
  namespace: du-subscriptions
spec:
  type: GitHub
  pathname: https://github.com/imiller0/ztp-ran-manifests
