apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cnfde2-cu-subscription
  namespace: cnfde2-cu-subscription
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - cnfde2-cu-subscription
